name: GitHub Actions Test
on: [pull_request]
jobs:
  test:
    name: Test1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Hello World
      run: echo "Hello World"